// <auto-generated />
using Data.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Efcore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Dto.MarketDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Market");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarketName = "Test Market"
                        });
                });

            modelBuilder.Entity("Entity.Dto.ProductDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BarcodeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "PROD-B4019871",
                            BarcodeNumber = "8690504111030",
                            MarketId = 1,
                            Price = 12.90m,
                            ProductName = "Ülker muzlu rondo"
                        },
                        new
                        {
                            Id = "PROD-652D25BE",
                            BarcodeNumber = "8690504087038",
                            MarketId = 1,
                            Price = 9.90m,
                            ProductName = "Ülker Can pare"
                        },
                        new
                        {
                            Id = "PROD-E8A02162",
                            BarcodeNumber = "8690504008002",
                            MarketId = 1,
                            Price = 10.90m,
                            ProductName = "Ülker çoko prens"
                        });
                });

            modelBuilder.Entity("Entity.Dto.ProductDto", b =>
                {
                    b.HasOne("Entity.Dto.MarketDto", "Market")
                        .WithMany("Products")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("Entity.Dto.MarketDto", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
